name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest
          ffmpeg-url: https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-release-essentials.zip

        - name: macOS
          os: macos-latest
          ffmpeg-url: https://evermeet.cx/ffmpeg/ffmpeg-6.0.zip

        - name: Android32
          os: ubuntu-latest
          target: Android32
          ffmpeg-url: https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-i686-static.tar.xz

        - name: Android64
          os: ubuntu-latest
          target: Android64
          ffmpeg-url: https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up FFmpeg
        run: |
          mkdir ffmpeg
          if [[ "${{ matrix.config.os }}" == "windows-latest" ]]; then
            curl -L ${{ matrix.config.ffmpeg-url }} -o ffmpeg.zip
            powershell -Command "Expand-Archive -Path ffmpeg.zip -DestinationPath ffmpeg -Force"
          elif [[ "${{ matrix.config.os }}" == "macos-latest" ]]; then
            curl -L ${{ matrix.config.ffmpeg-url }} -o ffmpeg.zip
            unzip -j ffmpeg.zip -d ffmpeg
          else
            curl -L ${{ matrix.config.ffmpeg-url }} | tar -xJ --strip-components=1 -C ffmpeg
          fi
        shell: bash

      - name: Add FFmpeg to PATH
        run: echo "FFMPEG_BIN=${{ github.workspace }}/ffmpeg/bin" >> $GITHUB_ENV
        shell: bash

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          bindings: geode-sdk/bindings
          bindings-ref: main
          combine: true
          sdk: nightly
          target: ${{ matrix.config.target }}

  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: ['build']

    steps:
      - name: Combine builds
        uses: geode-sdk/build-geode-mod/combine@main
        id: build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build Output
          path: ${{ steps.build.outputs.build-output }}
