name: Build Geode Mod - New

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest

        - name: macOS
          os: macos-latest

        - name: Android32
          os: ubuntu-latest
          target: Android32

        - name: Android64
          os: ubuntu-latest
          target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up FFmpeg for Windows
        if: matrix.config.name == 'Windows'
        run: |
          choco install ffmpeg

      - name: Set up FFmpeg for macOS
        if: matrix.config.name == 'macOS'
        run: |
          brew install ffmpeg

      - name: Set up Android SDK for Android32 and Android64
        if: matrix.config.name == 'Android32' || matrix.config.name == 'Android64'
        run: |
          # Install Android SDK tools
          sudo apt-get update
          sudo apt-get install -y android-sdk

          # Set up the ANDROID_SDK_HOME environment variable
          echo "ANDROID_SDK_HOME=/usr/lib/android-sdk" >> $GITHUB_ENV
          
          # Set the paths for Android SDK tools
          echo "ANDROID_HOME=/usr/lib/android-sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:/usr/lib/android-sdk/tools:/usr/lib/android-sdk/platform-tools" >> $GITHUB_ENV

          # Clone and build FFmpeg for Android
          git clone https://github.com/EclipseMenu/ffmpeg-android-maker/
          cd ffmpeg-android-maker
          ./ffmpeg-android-maker.sh --enable-libaom --enable-libvpx --enable-libx264 --enable-libx265 --android-api-level=24

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          bindings: geode-sdk/bindings
          bindings-ref: main
          combine: true
          sdk: nightly
          target: ${{ matrix.config.target }}

  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: ['build']

    steps:
      - uses: geode-sdk/build-geode-mod/combine@main
        id: build

      - uses: actions/upload-artifact@v4
        with:
          name: Build Output
          path: ${{ steps.build.outputs.build-output }}
